### ISSUE TITLE
Misleading return message from 'done' function during Module view

### ISSUE THREAD

**Issue by seanlowcy77** [AY1920S2-CS2103-T09-1/main#119]
Think return message should be 'You cannot complete a module' instead
<img width="997" alt="Screenshot 2020-04-05 at 3 42 14 AM" src="https://user-images.githubusercontent.com/52877163/78459983-b38f5d80-76ef-11ea-8cf4-8ef810f7b142.png">

**Comment by zhuhanming** [comment]
Hmm but if `done 1` refers to the list of deadlines on the right when listing `Events`, wouldn't `done 1` refer to the list of events on the right when viewing `Modules`?

**Comment by seanlowcy77** [comment]
Oh yea psps. Misunderstood
