### ISSUE TITLE
Done function makes deadlines undone as well 

### ISSUE THREAD

**Issue by seanlowcy77** [AY1920S2-CS2103-T09-1/main#120]
Entering 'done 1' again makes it marked as incomplete as well. oof
<img width="811" alt="Screenshot 2020-04-05 at 3 45 50 AM" src="https://user-images.githubusercontent.com/52877163/78460021-f3eedb80-76ef-11ea-8edd-c67ff6e94516.png">

**Comment by zhuhanming** [comment]
Isn't that the intended behaviour? Unless we separate it into `done` and `undone`.

**Comment by seanlowcy77** [comment]
Yeap my mistake!
